version: "3.2"
services:
  php:
    build: 
      context: .
    image: avinashkumar:11812851
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=ca-mysql-app
      - MYSQL_USER=avinashkumar
      - MYSQL_PASSWORD=11812851
      - MYSQL_DB=ca_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: ca-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=avinashkumar
      - MYSQL_PASSWORD=11812851
      - MYSQL_DATABASE=ca_db
    container_name: ca-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=ca-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: ca-phpmyadmin-app
networks:
  frontend:
  backend:
